//! Episodic Monte Carlo prediction and control on the shared Grid World.
//!
//! The implementation in this module is deliberately model-free at the
//! algorithm boundary: an episode is generated by interacting with a
//! [`GridWorldSession`], and action values are updated from complete sampled
//! returns.  The evaluator never reads a transition distribution while it is
//! learning.  The fixed Grid World is only used as an environment factory so
//! that the Chapter 1--5 experiments have the same terminal and reward
//! conventions.

use std::fmt;

use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha8Rng;

use crate::{Action, ConfigError, GoalMode, GridWorldConfig, GridWorldSession, Rewards};

pub const MONTE_CARLO_STATE_COUNT: usize = 16;
pub const MONTE_CARLO_ACTION_COUNT: usize = 5;
pub const MAX_MONTE_CARLO_EPISODES: u32 = 100_000;
pub const MAX_MONTE_CARLO_STEPS: u32 = 100;
pub const MAX_MONTE_CARLO_EPISODES_PER_ADVANCE: u32 = 2_000;
pub const MAX_MONTE_CARLO_HISTORY: usize = 100_000;
pub const MAX_MONTE_CARLO_REWARD_MAGNITUDE: f64 = 1_000_000.0;

const SHARED_GRID_SEED: u64 = 0x5eed;
const EXPLORING_START_ORDER_XOR: u64 = 0x4558_504c_4f52_4552;
const NUMERIC_TIE_TOLERANCE: f64 = 1e-12;

/// Which Monte Carlo control schedule is used for episode generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum MonteCarloMode {
    /// MC Basic: force a state--action start and use the initial visit by
    /// default.  The evaluator also accepts first/every visit for teaching
    /// comparisons.
    Basic = 0,
    /// MC Exploring Starts: sample a nonterminal state and action uniformly
    /// at the beginning of every episode.
    ExploringStarts = 1,
    /// MC epsilon-greedy: begin at the environment start and follow the
    /// current epsilon-soft policy.
    EpsilonGreedy = 2,
}

impl MonteCarloMode {
    pub const ALL: [Self; 3] = [Self::Basic, Self::ExploringStarts, Self::EpsilonGreedy];

    pub const fn code(self) -> u8 {
        self as u8
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Basic => "mc_basic",
            Self::ExploringStarts => "exploring_starts",
            Self::EpsilonGreedy => "epsilon_greedy",
        }
    }
}

impl TryFrom<&str> for MonteCarloMode {
    type Error = MonteCarloModeError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value.trim().to_ascii_lowercase().as_str() {
            "basic" | "mc-basic" | "mc_basic" | "mc_basic_control" | "mc-basic-control" => {
                Ok(Self::Basic)
            }
            "es" | "exploring-starts" | "exploring_starts" | "exploringstarts" => {
                Ok(Self::ExploringStarts)
            }
            "eg"
            | "epsilon"
            | "epsilon-greedy"
            | "epsilon_greedy"
            | "epsilon_greedy_control"
            | "epsilon-greedy-control" => Ok(Self::EpsilonGreedy),
            _ => Err(MonteCarloModeError::Unknown(value.to_owned())),
        }
    }
}

impl TryFrom<String> for MonteCarloMode {
    type Error = MonteCarloModeError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::try_from(value.as_str())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MonteCarloModeError {
    Unknown(String),
}

impl MonteCarloModeError {
    pub const fn code(&self) -> &'static str {
        "monte_carlo_mode"
    }
}

impl fmt::Display for MonteCarloModeError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unknown(value) => write!(formatter, "unknown Monte Carlo mode {value}"),
        }
    }
}

impl std::error::Error for MonteCarloModeError {}

/// How many returns from an episode are used for a state or state--action
/// estimate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum MonteCarloVisitStrategy {
    /// Only the first state--action pair of the episode.  This is the
    /// "initial-visit" strategy used by MC Basic in the book.
    Initial = 0,
    /// The first occurrence of each state or state--action pair.
    First = 1,
    /// Every occurrence of each state or state--action pair.
    Every = 2,
}

impl MonteCarloVisitStrategy {
    pub const ALL: [Self; 3] = [Self::Initial, Self::First, Self::Every];

    pub const fn code(self) -> u8 {
        self as u8
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Initial => "initial",
            Self::First => "first",
            Self::Every => "every",
        }
    }
}

impl TryFrom<&str> for MonteCarloVisitStrategy {
    type Error = MonteCarloVisitStrategyError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value.trim().to_ascii_lowercase().as_str() {
            "initial" | "initial-visit" | "initial_visit" | "start" => Ok(Self::Initial),
            "first" | "first-visit" | "first_visit" => Ok(Self::First),
            "every" | "every-visit" | "every_visit" => Ok(Self::Every),
            _ => Err(MonteCarloVisitStrategyError::Unknown(value.to_owned())),
        }
    }
}

impl TryFrom<String> for MonteCarloVisitStrategy {
    type Error = MonteCarloVisitStrategyError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::try_from(value.as_str())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MonteCarloVisitStrategyError {
    Unknown(String),
}

impl MonteCarloVisitStrategyError {
    pub const fn code(&self) -> &'static str {
        "monte_carlo_visit_strategy"
    }
}

impl fmt::Display for MonteCarloVisitStrategyError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unknown(value) => write!(formatter, "unknown Monte Carlo visit strategy {value}"),
        }
    }
}

impl std::error::Error for MonteCarloVisitStrategyError {}

/// Prediction leaves the behavior policy fixed; control performs greedy or
/// epsilon-soft policy improvement after each episode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum MonteCarloObjective {
    Prediction = 0,
    Control = 1,
}

impl MonteCarloObjective {
    pub const fn code(self) -> u8 {
        self as u8
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Prediction => "prediction",
            Self::Control => "control",
        }
    }
}

impl TryFrom<&str> for MonteCarloObjective {
    type Error = MonteCarloObjectiveError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value.trim().to_ascii_lowercase().as_str() {
            "prediction" | "predict" | "evaluation" => Ok(Self::Prediction),
            "control" | "improvement" | "learning" => Ok(Self::Control),
            _ => Err(MonteCarloObjectiveError::Unknown(value.to_owned())),
        }
    }
}

impl TryFrom<String> for MonteCarloObjective {
    type Error = MonteCarloObjectiveError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::try_from(value.as_str())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MonteCarloObjectiveError {
    Unknown(String),
}

impl MonteCarloObjectiveError {
    pub const fn code(&self) -> &'static str {
        "monte_carlo_objective"
    }
}

impl fmt::Display for MonteCarloObjectiveError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unknown(value) => write!(formatter, "unknown Monte Carlo objective {value}"),
        }
    }
}

impl std::error::Error for MonteCarloObjectiveError {}

/// Configuration for an episodic Monte Carlo run on the shared 4×4 world.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MonteCarloConfig {
    pub mode: MonteCarloMode,
    pub visit_strategy: MonteCarloVisitStrategy,
    pub objective: MonteCarloObjective,
    pub discount: f64,
    pub slip_probability: f64,
    pub epsilon: f64,
    pub episodes_per_step: u32,
    pub max_episodes: u32,
    pub max_steps: u32,
    pub seed: u64,
    pub rewards: Rewards,
}

impl Default for MonteCarloConfig {
    fn default() -> Self {
        Self {
            mode: MonteCarloMode::Basic,
            visit_strategy: MonteCarloVisitStrategy::Initial,
            objective: MonteCarloObjective::Control,
            discount: 0.9,
            slip_probability: 0.0,
            epsilon: 0.2,
            episodes_per_step: 1,
            max_episodes: 500,
            max_steps: MAX_MONTE_CARLO_STEPS,
            seed: SHARED_GRID_SEED,
            rewards: Rewards::default(),
        }
    }
}

impl MonteCarloConfig {
    pub fn validate(&self) -> Result<(), MonteCarloConfigError> {
        if !self.discount.is_finite() || !(0.0..=1.0).contains(&self.discount) {
            return Err(MonteCarloConfigError::Discount);
        }
        if !self.slip_probability.is_finite() || !(0.0..=1.0).contains(&self.slip_probability) {
            return Err(MonteCarloConfigError::SlipProbability);
        }
        if !self.epsilon.is_finite() || !(0.0..=1.0).contains(&self.epsilon) {
            return Err(MonteCarloConfigError::Epsilon);
        }
        if !(1..=MAX_MONTE_CARLO_EPISODES_PER_ADVANCE).contains(&self.episodes_per_step) {
            return Err(MonteCarloConfigError::EpisodesPerStep);
        }
        if !(1..=MAX_MONTE_CARLO_EPISODES).contains(&self.max_episodes) {
            return Err(MonteCarloConfigError::MaxEpisodes);
        }
        if !(1..=MAX_MONTE_CARLO_STEPS).contains(&self.max_steps) {
            return Err(MonteCarloConfigError::MaxSteps);
        }
        if [
            self.rewards.default,
            self.rewards.boundary,
            self.rewards.hazard,
            self.rewards.goal,
        ]
        .iter()
        .any(|reward| !reward.is_finite() || reward.abs() > MAX_MONTE_CARLO_REWARD_MAGNITUDE)
        {
            return Err(MonteCarloConfigError::Reward);
        }
        shared_world(*self)
            .validate()
            .map_err(MonteCarloConfigError::World)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MonteCarloConfigError {
    Discount,
    SlipProbability,
    Epsilon,
    EpisodesPerStep,
    MaxEpisodes,
    MaxSteps,
    Reward,
    World(ConfigError),
}

impl MonteCarloConfigError {
    pub const fn code(&self) -> &'static str {
        match self {
            Self::Discount => "monte_carlo_discount_range",
            Self::SlipProbability => "monte_carlo_slip_range",
            Self::Epsilon => "monte_carlo_epsilon_range",
            Self::EpisodesPerStep => "monte_carlo_episodes_per_step_range",
            Self::MaxEpisodes => "monte_carlo_max_episodes_range",
            Self::MaxSteps => "monte_carlo_max_steps_range",
            Self::Reward => "monte_carlo_reward_range",
            Self::World(error) => error.code(),
        }
    }
}

impl fmt::Display for MonteCarloConfigError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Discount => write!(formatter, "discount must be finite and in [0, 1]"),
            Self::SlipProbability => {
                write!(formatter, "slip_probability must be finite and in [0, 1]")
            }
            Self::Epsilon => write!(formatter, "epsilon must be finite and in [0, 1]"),
            Self::EpisodesPerStep => write!(
                formatter,
                "episodes_per_step must be between 1 and {MAX_MONTE_CARLO_EPISODES_PER_ADVANCE}"
            ),
            Self::MaxEpisodes => write!(
                formatter,
                "max_episodes must be between 1 and {MAX_MONTE_CARLO_EPISODES}"
            ),
            Self::MaxSteps => write!(
                formatter,
                "max_steps must be between 1 and {MAX_MONTE_CARLO_STEPS}"
            ),
            Self::Reward => write!(
                formatter,
                "rewards must be finite with magnitude at most {MAX_MONTE_CARLO_REWARD_MAGNITUDE}"
            ),
            Self::World(error) => error.fmt(formatter),
        }
    }
}

impl std::error::Error for MonteCarloConfigError {}

#[derive(Debug, Clone, PartialEq)]
pub enum MonteCarloError {
    Config(MonteCarloConfigError),
    EpisodeUnavailable,
    EpisodeGeneration(String),
}

impl MonteCarloError {
    pub const fn code(&self) -> &'static str {
        match self {
            Self::Config(error) => error.code(),
            Self::EpisodeUnavailable => "monte_carlo_episode_unavailable",
            Self::EpisodeGeneration(_) => "monte_carlo_episode_generation",
        }
    }
}

impl fmt::Display for MonteCarloError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Config(error) => error.fmt(formatter),
            Self::EpisodeUnavailable => {
                write!(formatter, "the configured episode budget is exhausted")
            }
            Self::EpisodeGeneration(error) => {
                write!(formatter, "could not generate episode: {error}")
            }
        }
    }
}

impl std::error::Error for MonteCarloError {}

impl From<MonteCarloConfigError> for MonteCarloError {
    fn from(error: MonteCarloConfigError) -> Self {
        Self::Config(error)
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
struct RunningStats {
    count: u32,
    sum: f64,
    mean: f64,
    m2: f64,
    min: f64,
    max: f64,
}

impl RunningStats {
    const fn new() -> Self {
        Self {
            count: 0,
            sum: 0.0,
            mean: 0.0,
            m2: 0.0,
            min: f64::INFINITY,
            max: f64::NEG_INFINITY,
        }
    }

    fn update(&mut self, value: f64) {
        if !value.is_finite() {
            return;
        }
        let next_count = self.count.saturating_add(1);
        if next_count == 0 {
            return;
        }
        self.count = next_count;
        self.sum += value;
        let delta = value - self.mean;
        self.mean += delta / self.count as f64;
        let delta_after = value - self.mean;
        self.m2 += delta * delta_after;
        self.min = self.min.min(value);
        self.max = self.max.max(value);
    }

    const fn variance(self) -> f64 {
        if self.count == 0 {
            0.0
        } else {
            // Round-off can leave a mathematically non-negative second
            // moment a few ulps below zero after a long replay.
            let variance = self.m2 / self.count as f64;
            if variance < 0.0 { 0.0 } else { variance }
        }
    }
}

/// One sampled transition in an episode.  `return_value` is filled after the
/// episode is complete and is the discounted suffix return beginning here.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MonteCarloStep {
    pub index: u32,
    pub state: u16,
    pub requested_action: Action,
    pub actual_action: Action,
    pub next_state: u16,
    pub reward: f64,
    pub discount_weight: f64,
    pub discounted_contribution: f64,
    pub return_value: f64,
    pub boundary_collision: bool,
    pub slipped: bool,
}

/// A single complete (or safety-truncated) episode and the estimates it
/// contributed to.
#[derive(Debug, Clone, PartialEq)]
pub struct MonteCarloEpisode {
    pub index: u32,
    pub start_state: u16,
    pub start_action: Action,
    pub steps: Vec<MonteCarloStep>,
    /// Discounted return from the initial state--action pair.
    pub return_value: f64,
    /// Alias retained in the core API for callers that use RL notation.
    pub discounted_return: f64,
    pub undiscounted_return: f64,
    pub terminated: bool,
    pub truncated: bool,
    pub updates: Vec<MonteCarloVisitUpdate>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct MonteCarloVisitUpdate {
    pub state: u16,
    pub action: Action,
    pub return_value: f64,
    pub visit_strategy: MonteCarloVisitStrategy,
    pub first_visit: bool,
    pub sample_count: u32,
    pub q_value: f64,
    pub variance: f64,
    pub policy_before: u8,
    pub policy_after: u8,
}

/// Full copyable state used by the Wasm adapter and replay UI.
#[derive(Debug, Clone, PartialEq)]
pub struct MonteCarloSnapshot {
    pub mode: MonteCarloMode,
    pub visit_strategy: MonteCarloVisitStrategy,
    pub objective: MonteCarloObjective,
    pub seed: u64,
    pub episode_count: u32,
    pub total_steps: u64,
    pub values: [f64; MONTE_CARLO_STATE_COUNT],
    pub q_values: [[f64; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT],
    /// Cumulative discounted-return sums for every state--action pair.
    pub returns: [[f64; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT],
    pub visits: [[u32; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT],
    pub variances: [[f64; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT],
    pub state_returns: [f64; MONTE_CARLO_STATE_COUNT],
    pub state_visits: [u32; MONTE_CARLO_STATE_COUNT],
    pub state_variances: [f64; MONTE_CARLO_STATE_COUNT],
    pub policy: [u8; MONTE_CARLO_STATE_COUNT],
    pub policy_masks: [u8; MONTE_CARLO_STATE_COUNT],
    pub greedy_masks: [u8; MONTE_CARLO_STATE_COUNT],
    pub policy_probabilities: [[f64; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT],
    pub episode_returns: Vec<f64>,
    pub episode_return_mean: f64,
    pub episode_return_variance: f64,
    pub last_episode_return: f64,
    pub last_episode_length: u32,
    pub last_episode_terminated: bool,
    pub last_episode_truncated: bool,
    pub last_policy_changes: u32,
    pub total_policy_changes: u64,
    pub last_update_max: f64,
    pub covered_state_actions: u32,
    pub exhausted: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct MonteCarloEpisodeOutcome {
    pub snapshot: MonteCarloSnapshot,
    pub episode: MonteCarloEpisode,
}

#[derive(Debug, Clone, PartialEq)]
pub struct MonteCarloAdvanceOutcome {
    pub snapshot: MonteCarloSnapshot,
    pub episodes: Vec<MonteCarloEpisode>,
    pub episode_returns: Vec<f64>,
}

/// Episodic MC evaluator/control engine.
#[derive(Debug, Clone)]
pub struct MonteCarloEvaluator {
    config: MonteCarloConfig,
    world: GridWorldConfig,
    rng: ChaCha8Rng,
    q_stats: [[RunningStats; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT],
    state_stats: [RunningStats; MONTE_CARLO_STATE_COUNT],
    episode_stats: RunningStats,
    policy: [Action; MONTE_CARLO_STATE_COUNT],
    episode_count: u32,
    total_steps: u64,
    basic_cursor: usize,
    episode_returns: Vec<f64>,
    last_episode: Option<MonteCarloEpisode>,
    last_policy_changes: u32,
    total_policy_changes: u64,
    last_update_max: f64,
    exploring_cursor: usize,
    /// A seeded permutation of legal state--action pair indices.  MC Basic
    /// uses a stable lexicographic sweep; Exploring Starts uses this separate
    /// permutation so the two teaching schedules remain observably distinct
    /// while still making coverage reproducible.
    exploring_order: Vec<usize>,
}

impl MonteCarloEvaluator {
    /// Construct the canonical 4×4 terminal Grid World evaluator.
    pub fn new(config: MonteCarloConfig) -> Result<Self, MonteCarloConfigError> {
        let world = shared_world(config);
        Self::with_world(config, world).map_err(|error| match error {
            MonteCarloError::Config(error) => error,
            MonteCarloError::EpisodeUnavailable | MonteCarloError::EpisodeGeneration(_) => {
                MonteCarloConfigError::World(ConfigError::GridSize { min: 2, max: 20 })
            }
        })
    }

    /// Construct an evaluator with a caller-supplied episodic world.  This is
    /// useful for native golden tests; the Wasm UI uses [`Self::new`].
    pub fn with_world(
        config: MonteCarloConfig,
        mut world: GridWorldConfig,
    ) -> Result<Self, MonteCarloError> {
        config.validate()?;
        world.validate().map_err(MonteCarloConfigError::World)?;
        // The public Chapter 5 payload has fixed 16×5 tensors.  Reject a
        // differently shaped custom world explicitly instead of allowing a
        // later state index to panic while updating those tensors.
        if world.width != 4 || world.height != 4 || world.goal != 15 {
            return Err(MonteCarloError::Config(MonteCarloConfigError::World(
                ConfigError::GridSize { min: 4, max: 4 },
            )));
        }
        if world.goal_mode != GoalMode::Terminate {
            return Err(MonteCarloError::Config(MonteCarloConfigError::World(
                ConfigError::Probability("goal_mode"),
            )));
        }
        world.hazards.sort_unstable();
        let policy = initial_policy(&world);
        Ok(Self {
            config,
            world,
            rng: ChaCha8Rng::seed_from_u64(config.seed),
            q_stats: [[RunningStats::new(); MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT],
            state_stats: [RunningStats::new(); MONTE_CARLO_STATE_COUNT],
            episode_stats: RunningStats::new(),
            policy,
            episode_count: 0,
            total_steps: 0,
            basic_cursor: 0,
            episode_returns: Vec::new(),
            last_episode: None,
            last_policy_changes: 0,
            total_policy_changes: 0,
            last_update_max: 0.0,
            exploring_cursor: 0,
            exploring_order: exploring_start_order(config.seed),
        })
    }

    pub const fn config(&self) -> MonteCarloConfig {
        self.config
    }

    pub const fn episode_count(&self) -> u32 {
        self.episode_count
    }

    pub fn world(&self) -> &GridWorldConfig {
        &self.world
    }

    pub fn snapshot(&self) -> MonteCarloSnapshot {
        let mut values = [0.0; MONTE_CARLO_STATE_COUNT];
        let mut q_values = [[0.0; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT];
        let mut returns = [[0.0; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT];
        let mut visits = [[0_u32; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT];
        let mut variances = [[0.0; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT];
        let mut state_returns = [0.0; MONTE_CARLO_STATE_COUNT];
        let mut state_visits = [0_u32; MONTE_CARLO_STATE_COUNT];
        let mut state_variances = [0.0; MONTE_CARLO_STATE_COUNT];
        let mut greedy_masks = [0_u8; MONTE_CARLO_STATE_COUNT];
        let mut policy_codes = [u8::MAX; MONTE_CARLO_STATE_COUNT];
        let mut policy_masks = [0_u8; MONTE_CARLO_STATE_COUNT];
        let mut policy_probabilities = [[0.0; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT];

        for state in 0..MONTE_CARLO_STATE_COUNT {
            state_returns[state] = self.state_stats[state].sum;
            state_visits[state] = self.state_stats[state].count;
            state_variances[state] = self.state_stats[state].variance();
            values[state] = self.state_stats[state].mean;
            if state as u16 == self.world.goal {
                continue;
            }
            let mut best = f64::NEG_INFINITY;
            for action in 0..MONTE_CARLO_ACTION_COUNT {
                let stats = self.q_stats[state][action];
                returns[state][action] = stats.sum;
                visits[state][action] = stats.count;
                variances[state][action] = stats.variance();
                q_values[state][action] = stats.mean;
                best = best.max(stats.mean);
            }
            let mut greedy_mask = 0_u8;
            for action in 0..MONTE_CARLO_ACTION_COUNT {
                if approximately_equal(self.q_stats[state][action].mean, best) {
                    greedy_mask |= 1_u8 << action;
                }
            }
            greedy_masks[state] = greedy_mask;
            let code = self.policy[state].code();
            policy_codes[state] = code;
            policy_masks[state] = 1_u8 << code;
            policy_probabilities[state] = self.policy_probabilities(state);
        }

        MonteCarloSnapshot {
            mode: self.config.mode,
            visit_strategy: self.config.visit_strategy,
            objective: self.config.objective,
            seed: self.config.seed,
            episode_count: self.episode_count,
            total_steps: self.total_steps,
            values,
            q_values,
            returns,
            visits,
            variances,
            state_returns,
            state_visits,
            state_variances,
            policy: policy_codes,
            policy_masks,
            greedy_masks,
            policy_probabilities,
            episode_returns: self.episode_returns.clone(),
            episode_return_mean: self.episode_stats.mean,
            episode_return_variance: self.episode_stats.variance(),
            last_episode_return: self
                .last_episode
                .as_ref()
                .map_or(0.0, |episode| episode.discounted_return),
            last_episode_length: self
                .last_episode
                .as_ref()
                .map_or(0, |episode| episode.steps.len() as u32),
            last_episode_terminated: self
                .last_episode
                .as_ref()
                .is_some_and(|episode| episode.terminated),
            last_episode_truncated: self
                .last_episode
                .as_ref()
                .is_some_and(|episode| episode.truncated),
            last_policy_changes: self.last_policy_changes,
            total_policy_changes: self.total_policy_changes,
            last_update_max: self.last_update_max,
            covered_state_actions: self
                .q_stats
                .iter()
                .flat_map(|row| row.iter())
                .filter(|stats| stats.count > 0)
                .count() as u32,
            exhausted: self.episode_count >= self.config.max_episodes,
        }
    }

    pub fn last_episode(&self) -> Option<&MonteCarloEpisode> {
        self.last_episode.as_ref()
    }

    /// Reset estimates and replay the same random stream when the seed is
    /// unchanged.  Passing `Some(seed)` updates the persisted seed.
    pub fn reset(&mut self, seed: Option<u64>) -> MonteCarloSnapshot {
        if let Some(seed) = seed {
            self.config.seed = seed;
        }
        self.rng = ChaCha8Rng::seed_from_u64(self.config.seed);
        self.q_stats = [[RunningStats::new(); MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT];
        self.state_stats = [RunningStats::new(); MONTE_CARLO_STATE_COUNT];
        self.episode_stats = RunningStats::new();
        self.policy = initial_policy(&self.world);
        self.episode_count = 0;
        self.total_steps = 0;
        self.basic_cursor = 0;
        self.episode_returns.clear();
        self.last_episode = None;
        self.last_policy_changes = 0;
        self.total_policy_changes = 0;
        self.last_update_max = 0.0;
        self.exploring_cursor = 0;
        self.exploring_order = exploring_start_order(self.config.seed);
        self.snapshot()
    }

    /// Generate and incorporate one episode.
    pub fn episode(&mut self) -> Result<MonteCarloEpisodeOutcome, MonteCarloError> {
        if self.episode_count >= self.config.max_episodes {
            return Err(MonteCarloError::EpisodeUnavailable);
        }
        let (start_state, start_action) = self.choose_start();
        let mut episode = self.generate_episode(start_state, start_action)?;
        self.update_from_episode(&mut episode);
        self.episode_count += 1;
        self.total_steps += episode.steps.len() as u64;
        self.episode_stats.update(episode.discounted_return);
        if self.episode_returns.len() < MAX_MONTE_CARLO_HISTORY {
            self.episode_returns.push(episode.discounted_return);
        }
        self.last_episode = Some(episode.clone());
        Ok(MonteCarloEpisodeOutcome {
            snapshot: self.snapshot(),
            episode,
        })
    }

    /// Generate up to `episodes` episodes, bounded by both the configured
    /// remaining budget and a per-call safety cap.
    pub fn advance(&mut self, episodes: u32) -> Result<MonteCarloAdvanceOutcome, MonteCarloError> {
        let requested = episodes.min(MAX_MONTE_CARLO_EPISODES_PER_ADVANCE);
        let remaining = self.config.max_episodes.saturating_sub(self.episode_count);
        let count = requested.min(remaining);
        let mut generated = Vec::with_capacity(count as usize);
        let mut returns = Vec::with_capacity(count as usize);
        for _ in 0..count {
            let outcome = self.episode()?;
            returns.push(outcome.episode.discounted_return);
            generated.push(outcome.episode);
        }
        Ok(MonteCarloAdvanceOutcome {
            snapshot: self.snapshot(),
            episodes: generated,
            episode_returns: returns,
        })
    }

    /// Advance by the configured batch size.
    pub fn step(&mut self) -> Result<MonteCarloAdvanceOutcome, MonteCarloError> {
        self.advance(self.config.episodes_per_step)
    }

    /// Run until the configured episode budget is exhausted.
    pub fn run_to_completion(&mut self) -> Result<MonteCarloAdvanceOutcome, MonteCarloError> {
        let mut all_episodes = Vec::new();
        let mut all_returns = Vec::new();
        while self.episode_count < self.config.max_episodes {
            let remaining = self.config.max_episodes.saturating_sub(self.episode_count);
            let chunk = remaining.min(MAX_MONTE_CARLO_EPISODES_PER_ADVANCE);
            let outcome = self.advance(chunk)?;
            if outcome.episodes.is_empty() {
                break;
            }
            all_returns.extend(outcome.episode_returns);
            all_episodes.extend(outcome.episodes);
        }
        Ok(MonteCarloAdvanceOutcome {
            snapshot: self.snapshot(),
            episodes: all_episodes,
            episode_returns: all_returns,
        })
    }

    fn choose_start(&mut self) -> (u16, Action) {
        match self.config.mode {
            MonteCarloMode::Basic => {
                let pair_count = (MONTE_CARLO_STATE_COUNT - 1) * MONTE_CARLO_ACTION_COUNT;
                let pair = self.basic_cursor % pair_count;
                self.basic_cursor = self.basic_cursor.wrapping_add(1);
                (
                    (pair / MONTE_CARLO_ACTION_COUNT) as u16,
                    Action::ALL[pair % MONTE_CARLO_ACTION_COUNT],
                )
            }
            MonteCarloMode::ExploringStarts => {
                // A seeded permutation makes the exploring-starts schedule
                // auditable without collapsing it into MC Basic's fixed
                // lexicographic sweep.  Every legal pair still appears once
                // per cycle, and the same seed reproduces the permutation.
                let pair_count = self.exploring_order.len();
                let pair = self.exploring_order[self.exploring_cursor % pair_count];
                self.exploring_cursor = self.exploring_cursor.wrapping_add(1);
                (
                    (pair / MONTE_CARLO_ACTION_COUNT) as u16,
                    Action::ALL[pair % MONTE_CARLO_ACTION_COUNT],
                )
            }
            MonteCarloMode::EpsilonGreedy => {
                let state = self.world.start;
                let action = self.sample_policy_action(state);
                (state, action)
            }
        }
    }

    fn generate_episode(
        &mut self,
        start_state: u16,
        start_action: Action,
    ) -> Result<MonteCarloEpisode, MonteCarloError> {
        let episode_seed = self.rng.random::<u64>();
        let mut world = self.world.clone();
        world.seed = episode_seed;
        let mut session = GridWorldSession::new_at_state(world, start_state)
            .map_err(|error| MonteCarloError::EpisodeGeneration(error.to_string()))?;
        let mut steps = Vec::with_capacity(self.config.max_steps as usize);
        let mut requested_action = start_action;
        for index in 0..self.config.max_steps {
            let outcome = session
                .step(requested_action)
                .map_err(|error| MonteCarloError::EpisodeGeneration(error.to_string()))?;
            steps.push(MonteCarloStep {
                index,
                state: outcome.previous_state,
                requested_action: outcome.requested_action,
                actual_action: outcome.actual_action,
                next_state: outcome.next_state,
                reward: outcome.reward,
                discount_weight: self.config.discount.powi(index as i32),
                discounted_contribution: self.config.discount.powi(index as i32) * outcome.reward,
                return_value: 0.0,
                boundary_collision: outcome.boundary_collision,
                slipped: outcome.slipped,
            });
            if outcome.done || outcome.truncated {
                break;
            }
            requested_action = self.next_action(outcome.next_state);
        }

        let mut suffix_return = 0.0;
        for step in steps.iter_mut().rev() {
            suffix_return = step.reward + self.config.discount * suffix_return;
            step.return_value = suffix_return;
        }
        let discounted_return = steps.first().map_or(0.0, |step| step.return_value);
        let undiscounted_return = steps.iter().map(|step| step.reward).sum();
        let terminated = steps
            .last()
            .is_some_and(|step| step.next_state == self.world.goal);
        let truncated = !terminated && steps.len() >= self.config.max_steps as usize;
        Ok(MonteCarloEpisode {
            index: self.episode_count,
            start_state,
            start_action,
            steps,
            return_value: discounted_return,
            discounted_return,
            undiscounted_return,
            terminated,
            truncated,
            updates: Vec::new(),
        })
    }

    fn next_action(&mut self, state: u16) -> Action {
        if self.config.mode == MonteCarloMode::EpsilonGreedy {
            self.sample_policy_action(state)
        } else {
            self.policy[state as usize]
        }
    }

    fn sample_policy_action(&mut self, state: u16) -> Action {
        let probabilities = self.policy_probabilities(state as usize);
        let draw = self.rng.random::<f64>();
        let mut cumulative = 0.0;
        for (index, probability) in probabilities.iter().enumerate() {
            cumulative += probability;
            if draw < cumulative {
                return Action::ALL[index];
            }
        }
        Action::Stay
    }

    fn policy_probabilities(&self, state: usize) -> [f64; MONTE_CARLO_ACTION_COUNT] {
        let mut probabilities = [0.0; MONTE_CARLO_ACTION_COUNT];
        if state >= MONTE_CARLO_STATE_COUNT || state as u16 == self.world.goal {
            return probabilities;
        }
        let greedy = self.policy[state] as usize;
        if self.config.mode == MonteCarloMode::EpsilonGreedy {
            let exploratory = self.config.epsilon / MONTE_CARLO_ACTION_COUNT as f64;
            probabilities.fill(exploratory);
            probabilities[greedy] += 1.0 - self.config.epsilon;
        } else {
            probabilities[greedy] = 1.0;
        }
        probabilities
    }

    fn update_from_episode(&mut self, episode: &mut MonteCarloEpisode) {
        let mut first_state_seen = [false; MONTE_CARLO_STATE_COUNT];
        let mut first_pair_seen = [[false; MONTE_CARLO_ACTION_COUNT]; MONTE_CARLO_STATE_COUNT];
        let mut affected_states = [false; MONTE_CARLO_STATE_COUNT];
        let mut selected = vec![false; episode.steps.len()];
        let mut pair_first_flags = vec![false; episode.steps.len()];
        for (index, step) in episode.steps.iter().enumerate() {
            let state = step.state as usize;
            let action = step.requested_action as usize;
            let pair_first = !first_pair_seen[state][action];
            let state_first = !first_state_seen[state];
            first_pair_seen[state][action] = true;
            first_state_seen[state] = true;
            pair_first_flags[index] = pair_first;
            selected[index] = match self.config.visit_strategy {
                MonteCarloVisitStrategy::Initial => index == 0,
                MonteCarloVisitStrategy::First => pair_first,
                MonteCarloVisitStrategy::Every => true,
            };
            if selected[index] {
                affected_states[state] = true;
                let state_selected = match self.config.visit_strategy {
                    MonteCarloVisitStrategy::Initial => index == 0,
                    MonteCarloVisitStrategy::First => state_first,
                    MonteCarloVisitStrategy::Every => true,
                };
                if state_selected {
                    self.state_stats[state].update(step.return_value);
                }
            }
        }

        let mut pending: Vec<(usize, usize, f64, bool)> = Vec::new();
        for (index, step) in episode.steps.iter().enumerate() {
            if selected[index] {
                pending.push((
                    step.state as usize,
                    step.requested_action as usize,
                    step.return_value,
                    pair_first_flags[index],
                ));
            }
        }
        // The book's pseudocode accumulates returns from T−1 down to 0.  The
        // sample values are already computed in one reverse pass; applying
        // them in reverse preserves that observable order in the trace.
        pending.reverse();
        let mut max_update: f64 = 0.0;
        for (state, action, return_value, initial) in pending {
            let before = self.q_stats[state][action].mean;
            self.q_stats[state][action].update(return_value);
            let after = self.q_stats[state][action].mean;
            max_update = max_update.max((after - before).abs());
            let policy_before = self.policy[state].code();
            episode.updates.push(MonteCarloVisitUpdate {
                state: state as u16,
                action: Action::ALL[action],
                return_value,
                visit_strategy: self.config.visit_strategy,
                first_visit: initial,
                sample_count: self.q_stats[state][action].count,
                q_value: after,
                variance: self.q_stats[state][action].variance(),
                policy_before,
                policy_after: policy_before,
            });
        }

        let mut policy_changes = 0_u32;
        if self.config.objective == MonteCarloObjective::Control {
            for (state, is_affected) in affected_states.into_iter().enumerate() {
                if !is_affected || state as u16 == self.world.goal {
                    continue;
                }
                let before = self.policy[state];
                let after = self.greedy_action(state);
                self.policy[state] = after;
                if before != after {
                    policy_changes += 1;
                }
                for update in episode
                    .updates
                    .iter_mut()
                    .filter(|update| update.state as usize == state)
                {
                    update.policy_before = before.code();
                    update.policy_after = after.code();
                }
            }
        }
        self.last_policy_changes = policy_changes;
        self.total_policy_changes += policy_changes as u64;
        self.last_update_max = max_update;
    }

    fn greedy_action(&self, state: usize) -> Action {
        let mut best = f64::NEG_INFINITY;
        let mut action = Action::Up;
        for candidate in Action::ALL {
            let value = self.q_stats[state][candidate as usize].mean;
            if value > best + NUMERIC_TIE_TOLERANCE {
                best = value;
                action = candidate;
            }
        }
        action
    }
}

/// A tiny iid ±1 estimator used by the Chapter 5 motivating example.  It
/// shares the named ChaCha RNG convention with episodic MC and exposes the
/// running mean and variance so the law-of-large-numbers picture is numeric.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MeanEstimationConfig {
    pub seed: u64,
    pub max_samples: u32,
}

impl Default for MeanEstimationConfig {
    fn default() -> Self {
        Self {
            seed: SHARED_GRID_SEED,
            max_samples: 1_000,
        }
    }
}

impl MeanEstimationConfig {
    pub fn validate(&self) -> Result<(), MeanEstimationConfigError> {
        if self.max_samples == 0 || self.max_samples > MAX_MONTE_CARLO_EPISODES {
            return Err(MeanEstimationConfigError::MaxSamples);
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MeanEstimationConfigError {
    MaxSamples,
}

impl MeanEstimationConfigError {
    pub const fn code(&self) -> &'static str {
        "mean_max_samples_range"
    }
}

impl fmt::Display for MeanEstimationConfigError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "max_samples must be between 1 and {MAX_MONTE_CARLO_EPISODES}"
        )
    }
}

impl std::error::Error for MeanEstimationConfigError {}

#[derive(Debug, Clone, PartialEq)]
pub struct MeanEstimationSnapshot {
    pub seed: u64,
    pub sample_count: u32,
    pub samples: Vec<f64>,
    pub mean: f64,
    pub variance: f64,
    pub expected_mean: f64,
    pub exhausted: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct MeanEstimationOutcome {
    pub snapshot: MeanEstimationSnapshot,
    pub new_samples: Vec<f64>,
}

#[derive(Debug, Clone)]
pub struct MeanEstimator {
    config: MeanEstimationConfig,
    rng: ChaCha8Rng,
    stats: RunningStats,
    samples: Vec<f64>,
}

impl MeanEstimator {
    pub fn new(config: MeanEstimationConfig) -> Result<Self, MeanEstimationConfigError> {
        config.validate()?;
        Ok(Self {
            config,
            rng: ChaCha8Rng::seed_from_u64(config.seed),
            stats: RunningStats::new(),
            samples: Vec::new(),
        })
    }

    pub const fn config(&self) -> MeanEstimationConfig {
        self.config
    }

    pub fn snapshot(&self) -> MeanEstimationSnapshot {
        MeanEstimationSnapshot {
            seed: self.config.seed,
            sample_count: self.stats.count,
            samples: self.samples.clone(),
            mean: self.stats.mean,
            variance: self.stats.variance(),
            expected_mean: 0.0,
            exhausted: self.stats.count >= self.config.max_samples,
        }
    }

    pub fn reset(&mut self, seed: Option<u64>) -> MeanEstimationSnapshot {
        if let Some(seed) = seed {
            self.config.seed = seed;
        }
        self.rng = ChaCha8Rng::seed_from_u64(self.config.seed);
        self.stats = RunningStats::new();
        self.samples.clear();
        self.snapshot()
    }

    pub fn advance(&mut self, count: u32) -> MeanEstimationOutcome {
        let remaining = self.config.max_samples.saturating_sub(self.stats.count);
        let amount = count.min(remaining);
        let mut new_samples = Vec::with_capacity(amount as usize);
        for _ in 0..amount {
            let sample = if self.rng.random::<f64>() < 0.5 {
                -1.0
            } else {
                1.0
            };
            self.stats.update(sample);
            self.samples.push(sample);
            new_samples.push(sample);
        }
        MeanEstimationOutcome {
            snapshot: self.snapshot(),
            new_samples,
        }
    }

    pub fn sample(&mut self) -> MeanEstimationOutcome {
        self.advance(1)
    }
}

fn shared_world(config: MonteCarloConfig) -> GridWorldConfig {
    GridWorldConfig {
        width: 4,
        height: 4,
        start: 0,
        goal: 15,
        goal_mode: GoalMode::Terminate,
        hazards: vec![6, 9],
        rewards: config.rewards,
        slip_probability: config.slip_probability,
        discount: config.discount,
        seed: config.seed,
    }
}

fn exploring_start_order(seed: u64) -> Vec<usize> {
    let pair_count = (MONTE_CARLO_STATE_COUNT - 1) * MONTE_CARLO_ACTION_COUNT;
    let mut order: Vec<usize> = (0..pair_count).collect();
    let mut rng = ChaCha8Rng::seed_from_u64(seed ^ EXPLORING_START_ORDER_XOR);
    for index in (1..order.len()).rev() {
        let swap = rng.random_range(0..=index);
        order.swap(index, swap);
    }
    order
}

fn initial_policy(world: &GridWorldConfig) -> [Action; MONTE_CARLO_STATE_COUNT] {
    let mut policy = [Action::Stay; MONTE_CARLO_STATE_COUNT];
    let width = world.width as u16;
    for (state, action_slot) in policy.iter_mut().enumerate() {
        let state_u16 = state as u16;
        if state_u16 == world.goal {
            continue;
        }
        let row = state_u16 / width;
        let column = state_u16 % width;
        *action_slot = if column + 1 < width {
            Action::Right
        } else if row + 1 < world.height as u16 {
            Action::Down
        } else {
            Action::Left
        };
    }
    policy
}

fn approximately_equal(left: f64, right: f64) -> bool {
    (left - right).abs() <= NUMERIC_TIE_TOLERANCE * left.abs().max(right.abs()).max(1.0)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config() -> MonteCarloConfig {
        MonteCarloConfig {
            mode: MonteCarloMode::Basic,
            visit_strategy: MonteCarloVisitStrategy::Initial,
            objective: MonteCarloObjective::Control,
            discount: 0.9,
            slip_probability: 0.0,
            epsilon: 0.2,
            episodes_per_step: 1,
            max_episodes: 100,
            max_steps: 20,
            seed: 0x5eed,
            rewards: Rewards::default(),
        }
    }

    #[test]
    fn parses_public_mode_and_visit_aliases() {
        assert_eq!(
            MonteCarloMode::try_from("mc-basic"),
            Ok(MonteCarloMode::Basic)
        );
        assert_eq!(
            MonteCarloMode::try_from("ES"),
            Ok(MonteCarloMode::ExploringStarts)
        );
        assert_eq!(
            MonteCarloMode::try_from("epsilon_greedy"),
            Ok(MonteCarloMode::EpsilonGreedy)
        );
        assert_eq!(
            MonteCarloVisitStrategy::try_from("initial"),
            Ok(MonteCarloVisitStrategy::Initial)
        );
        assert_eq!(
            MonteCarloVisitStrategy::try_from("first_visit"),
            Ok(MonteCarloVisitStrategy::First)
        );
        assert_eq!(
            MonteCarloVisitStrategy::try_from("every-visit"),
            Ok(MonteCarloVisitStrategy::Every)
        );
    }

    #[test]
    fn mean_estimation_is_seeded_and_reset_replays_samples() {
        let mut estimator = MeanEstimator::new(MeanEstimationConfig {
            seed: 0x1234,
            max_samples: 20,
        })
        .expect("valid mean config");
        let first = estimator.advance(8).snapshot.samples;
        estimator.reset(None);
        let second = estimator.advance(8).snapshot.samples;
        assert_eq!(first, second);
        assert_eq!(first.len(), 8);
        assert!(estimator.snapshot().variance >= 0.0);
    }

    #[test]
    fn basic_initial_visit_updates_only_the_initial_pair() {
        let mut evaluator = MonteCarloEvaluator::new(config()).expect("valid config");
        let outcome = evaluator.episode().expect("episode generated");
        assert_eq!(outcome.episode.start_state, 0);
        assert_eq!(outcome.episode.start_action, Action::Up);
        assert_eq!(outcome.episode.updates.len(), 1);
        assert_eq!(outcome.episode.updates[0].state, 0);
        assert_eq!(outcome.episode.updates[0].action, Action::Up);
        assert_eq!(outcome.snapshot.episode_count, 1);
        assert!(outcome.snapshot.visits[0][Action::Up as usize] == 1);
    }

    #[test]
    fn first_and_every_visit_have_expected_update_counts_on_a_loop() {
        let mut first_config = config();
        first_config.visit_strategy = MonteCarloVisitStrategy::First;
        first_config.max_steps = 4;
        let mut first = MonteCarloEvaluator::new(first_config).expect("valid config");
        let first_outcome = first.episode().expect("episode generated");
        let first_pairs: usize = first_outcome
            .episode
            .updates
            .iter()
            .map(|update| update.state as usize * 5 + update.action as usize)
            .collect::<std::collections::BTreeSet<_>>()
            .len();
        assert_eq!(first_pairs, first_outcome.episode.updates.len());
        assert!(
            first_outcome
                .episode
                .updates
                .iter()
                .all(|update| update.first_visit)
        );

        let mut every_config = first_config;
        every_config.visit_strategy = MonteCarloVisitStrategy::Every;
        let mut every = MonteCarloEvaluator::new(every_config).expect("valid config");
        let every_outcome = every.episode().expect("episode generated");
        assert!(every_outcome.episode.updates.len() >= first_outcome.episode.updates.len());
        let mut seen_pairs = std::collections::BTreeSet::new();
        for update in &every_outcome.episode.updates {
            let pair = (update.state, update.action as u8);
            assert_eq!(update.first_visit, seen_pairs.insert(pair));
        }
    }

    #[test]
    fn exploring_starts_cycles_through_all_start_pairs() {
        let mut cfg = config();
        cfg.mode = MonteCarloMode::ExploringStarts;
        cfg.visit_strategy = MonteCarloVisitStrategy::Initial;
        cfg.max_episodes = 100;
        let mut evaluator = MonteCarloEvaluator::new(cfg).expect("valid config");
        let mut starts = Vec::new();
        for _ in 0..75 {
            let out = evaluator.episode().expect("episode");
            starts.push((out.episode.start_state, out.episode.start_action));
        }
        starts.sort_unstable_by_key(|(state, action)| (*state, *action as u8));
        starts.dedup();
        assert_eq!(starts.len(), 75);
        assert!(starts.iter().all(|(state, _)| *state < 15));
    }

    #[test]
    fn basic_and_exploring_starts_have_distinct_reproducible_schedules() {
        let mut basic_cfg = config();
        basic_cfg.max_steps = 1;
        let mut basic = MonteCarloEvaluator::new(basic_cfg).expect("valid config");
        let basic_starts: Vec<_> = (0..4)
            .map(|_| basic.episode().expect("basic episode").episode.start_state)
            .collect();

        let mut exploring_cfg = basic_cfg;
        exploring_cfg.mode = MonteCarloMode::ExploringStarts;
        let mut exploring = MonteCarloEvaluator::new(exploring_cfg).expect("valid config");
        let exploring_starts: Vec<_> = (0..4)
            .map(|_| {
                exploring
                    .episode()
                    .expect("exploring episode")
                    .episode
                    .start_state
            })
            .collect();
        assert_ne!(basic_starts, exploring_starts);

        exploring.reset(None);
        let replayed: Vec<_> = (0..4)
            .map(|_| {
                exploring
                    .episode()
                    .expect("replayed episode")
                    .episode
                    .start_state
            })
            .collect();
        assert_eq!(exploring_starts, replayed);
    }

    #[test]
    fn epsilon_greedy_policy_probabilities_are_soft_and_normalized() {
        let mut cfg = config();
        cfg.mode = MonteCarloMode::EpsilonGreedy;
        cfg.epsilon = 0.2;
        let evaluator = MonteCarloEvaluator::new(cfg).expect("valid config");
        let probabilities = evaluator.snapshot().policy_probabilities[0];
        assert!((probabilities.iter().sum::<f64>() - 1.0).abs() < 1e-12);
        assert!(probabilities.iter().all(|probability| *probability > 0.0));
        assert!((probabilities[Action::Right as usize] - 0.84).abs() < 1e-12);
    }

    #[test]
    fn replay_after_reset_is_bitwise_identical_for_episode_and_snapshot() {
        let mut evaluator = MonteCarloEvaluator::new(config()).expect("valid config");
        let first = evaluator.advance(5).expect("advance");
        evaluator.reset(None);
        let second = evaluator.advance(5).expect("advance");
        assert_eq!(first, second);
    }

    #[test]
    fn terminal_goal_is_not_counted_as_a_decision_pair() {
        let mut cfg = config();
        cfg.mode = MonteCarloMode::EpsilonGreedy;
        cfg.epsilon = 0.0;
        let mut evaluator = MonteCarloEvaluator::new(cfg).expect("valid config");
        let outcome = evaluator.episode().expect("episode");
        let snapshot = outcome.snapshot;
        assert_eq!(snapshot.policy[15], u8::MAX);
        assert_eq!(snapshot.policy_masks[15], 0);
        assert_eq!(snapshot.visits[15], [0; 5]);
        assert!(outcome.episode.terminated);
    }

    #[test]
    fn arbitrary_exploring_start_can_be_a_hazard_without_changing_hazard_reward() {
        let mut world = shared_world(config());
        world.seed = 0x1234;
        let mut session = GridWorldSession::new_at_state(world, 6).expect("hazard is legal start");
        let outcome = session.step(Action::Stay).expect("active episode");
        assert_eq!(outcome.previous_state, 6);
        assert_eq!(outcome.next_state, 6);
        assert_eq!(outcome.reward, -1.0);
    }

    #[test]
    fn returns_are_computed_by_a_reverse_discounted_pass() {
        let mut cfg = config();
        cfg.mode = MonteCarloMode::Basic;
        cfg.objective = MonteCarloObjective::Prediction;
        cfg.discount = 0.5;
        cfg.max_steps = 2;
        cfg.rewards = Rewards {
            default: 1.0,
            boundary: 1.0,
            hazard: 1.0,
            goal: 1.0,
        };
        let mut evaluator = MonteCarloEvaluator::new(cfg).expect("valid config");
        let episode = evaluator.episode().expect("episode").episode;
        assert_eq!(episode.steps.len(), 2);
        assert!((episode.steps[1].return_value - 1.0).abs() < f64::EPSILON);
        assert!((episode.steps[0].return_value - 1.5).abs() < f64::EPSILON);
        assert!((episode.discounted_return - 1.5).abs() < f64::EPSILON);
    }

    #[test]
    fn run_to_completion_drains_more_than_one_advance_chunk() {
        let mut cfg = config();
        cfg.max_episodes = MAX_MONTE_CARLO_EPISODES_PER_ADVANCE + 7;
        cfg.max_steps = 1;
        let mut evaluator = MonteCarloEvaluator::new(cfg).expect("valid config");
        let outcome = evaluator.run_to_completion().expect("run completes");
        assert_eq!(outcome.episodes.len(), cfg.max_episodes as usize);
        assert_eq!(outcome.episode_returns.len(), cfg.max_episodes as usize);
        assert_eq!(outcome.snapshot.episode_count, cfg.max_episodes);
    }

    #[test]
    fn validates_episode_and_epsilon_bounds() {
        let mut invalid = config();
        invalid.epsilon = 1.1;
        assert_eq!(invalid.validate(), Err(MonteCarloConfigError::Epsilon));
        invalid = config();
        invalid.max_steps = 0;
        assert_eq!(invalid.validate(), Err(MonteCarloConfigError::MaxSteps));
    }

    #[test]
    fn rejects_custom_world_shapes_that_do_not_fit_the_public_tensor() {
        let mut world = shared_world(config());
        world.width = 2;
        world.height = 2;
        world.goal = 3;
        world.hazards.clear();
        let error = MonteCarloEvaluator::with_world(config(), world).expect_err("shape rejected");
        assert!(matches!(
            error,
            MonteCarloError::Config(MonteCarloConfigError::World(ConfigError::GridSize {
                min: 4,
                max: 4
            }))
        ));
    }
}
