/// <reference lib="webworker" />

/* Chapter 8 value-function Worker adapter. */
import init, * as wasmModule from '../generated/wasm/mathrl_wasm.js'
import {
  VALUE_FUNCTION_PROTOCOL_VERSION,
  canonicalValueFunctionFeatureMap,
  canonicalValueFunctionMode,
  valueFunctionConfigValidationError,
  type ValueFunctionAdvanceOutcome,
  type ValueFunctionAudit,
  type ValueFunctionConfig,
  type ValueFunctionEpisode,
  type ValueFunctionMode,
  type ValueFunctionOutcome,
  type ValueFunctionSnapshot,
  type ValueFunctionUpdate,
  type ValueFunctionWorkerRequest,
  type ValueFunctionWorkerResponse,
  type ValueFunctionTransition,
} from '../valueFunctionProtocol'

const scope: DedicatedWorkerGlobalScope = self as unknown as DedicatedWorkerGlobalScope
type RecordLike = Record<string, unknown>
type WasmEvaluator = RecordLike & { free?: () => void }
type WasmConstructor = new (...args: unknown[]) => WasmEvaluator
let evaluator: WasmEvaluator | undefined
let initPromise: Promise<void> | undefined
let activeRunId = ''
let sequence = 0
let config: ValueFunctionConfig | undefined

function record(value: unknown): RecordLike | undefined { return value && typeof value === 'object' ? value as RecordLike : undefined }
function valueAt(source: RecordLike | undefined, ...keys: string[]): unknown { if (!source) return undefined; for (const key of keys) if (key in source) return source[key]; return undefined }
function numberAt(source: RecordLike | undefined, fallback: number, ...keys: string[]): number { const value = valueAt(source, ...keys); const parsed = typeof value === 'number' ? value : Number(value); return Number.isFinite(parsed) ? parsed : fallback }
function boolAt(source: RecordLike | undefined, fallback: boolean, ...keys: string[]): boolean { const value = valueAt(source, ...keys); return typeof value === 'boolean' ? value : fallback }
function arrayAt(source: RecordLike | undefined, ...keys: string[]): unknown[] { const value = valueAt(source, ...keys); return Array.isArray(value) ? value : [] }
function finiteArray(value: unknown, length: number): number[] { const source = Array.isArray(value) ? value : []; return Array.from({ length }, (_, index) => { const parsed = typeof source[index] === 'number' ? source[index] as number : Number(source[index]); return Number.isFinite(parsed) ? parsed : 0 }) }
async function ensureInit(): Promise<void> { initPromise ??= init().then(() => undefined).catch((error: unknown) => { initPromise = undefined; throw error }); await initPromise }
function constructor(): WasmConstructor | undefined { const candidate = (wasmModule as RecordLike).ValueFunctionEvaluator; return typeof candidate === 'function' ? candidate as WasmConstructor : undefined }
function instantiate(next: ValueFunctionConfig): WasmEvaluator {
  const Ctor = constructor(); if (!Ctor) throw new Error('ValueFunctionEvaluator is missing from the Wasm bundle')
  return new Ctor(next.mode, next.featureMap, next.discount, next.slipProbability, next.epsilon, next.alpha, next.replayCapacity, next.batchSize, next.targetUpdateInterval, next.maxEpisodes, next.maxSteps, next.seedHex, next.rewards.default, next.rewards.boundary, next.rewards.hazard, next.rewards.goal)
}
function call(target: WasmEvaluator, names: string[], ...args: unknown[]): unknown { for (const name of names) { const method = target[name]; if (typeof method === 'function') return (method as (...values: unknown[]) => unknown).apply(target, args) }; throw new Error(`Wasm evaluator method is missing: ${names.join('/')}`) }
function action(value: unknown, fallback = 4): number { if (typeof value === 'string') { const map: Record<string, number> = { up: 0, right: 1, down: 2, left: 3, stay: 4 }; const mapped = map[value.toLowerCase()]; if (mapped !== undefined) return mapped; const parsed = Number(value); return Number.isInteger(parsed) ? parsed : fallback }; const parsed = Number(value); return Number.isInteger(parsed) && parsed >= 0 && parsed <= 4 ? parsed : fallback }
function normalizeTransition(value: unknown, index = 0): ValueFunctionTransition { const source = record(value); const requested = action(valueAt(source, 'action', 'requestedAction', 'requested_action')); return { episodeStep: numberAt(source, index, 'episodeStep', 'episode_step', 'step', 'index'), state: numberAt(source, 0, 'state', 'previousState', 'previous_state'), action: requested as ValueFunctionTransition['action'], actualAction: action(valueAt(source, 'actualAction', 'actual_action'), requested) as ValueFunctionTransition['actualAction'], nextState: numberAt(source, 0, 'nextState', 'next_state'), reward: numberAt(source, 0, 'reward'), done: boolAt(source, false, 'done', 'terminated'), truncated: boolAt(source, false, 'truncated') } }
function normalizeUpdate(value: unknown, index = 0): ValueFunctionUpdate { const source = record(value); return { episode: numberAt(source, 1, 'episode'), index: numberAt(source, index, 'index', 'step'), state: numberAt(source, 0, 'state'), action: action(valueAt(source, 'action'), 255), features: finiteArray(valueAt(source, 'features', 'featureVector', 'feature_vector'), 16), featureCount: numberAt(source, 0, 'featureCount', 'feature_count'), prediction: numberAt(source, 0, 'prediction', 'value'), target: numberAt(source, 0, 'target', 'tdTarget', 'td_target'), tdError: numberAt(source, 0, 'tdError', 'td_error', 'error'), loss: numberAt(source, 0, 'loss'), gradientNorm: numberAt(source, 0, 'gradientNorm', 'gradient_norm'), updateNorm: numberAt(source, 0, 'updateNorm', 'update_norm'), replaySize: numberAt(source, 0, 'replaySize', 'replay_size'), targetSynced: boolAt(source, false, 'targetSynced', 'target_synced') } }
function normalizeSnapshot(value: unknown, fallback: ValueFunctionConfig): ValueFunctionSnapshot { const source = record(value); const rawActionValues = arrayAt(source, 'actionValues', 'action_values', 'qValues', 'q_values'); const rawPolicy = finiteArray(valueAt(source, 'policy'), 16).map((number) => Math.trunc(number)); return { mode: canonicalValueFunctionMode(valueAt(source, 'mode')) ?? fallback.mode, featureMap: canonicalValueFunctionFeatureMap(valueAt(source, 'featureMap', 'feature_map')) ?? fallback.featureMap, featureCount: numberAt(source, fallback.featureMap === 'coordinates' ? 2 : fallback.featureMap === 'bias_coordinates' ? 3 : fallback.featureMap === 'polynomial' ? 6 : fallback.featureMap === 'fourier' ? 9 : 16, 'featureCount', 'feature_count'), weights: finiteArray(valueAt(source, 'weights'), 16), actionWeights: Array.from({ length: 5 }, (_, actionIndex) => finiteArray(arrayAt(source, 'actionWeights', 'action_weights')[actionIndex], 16)), targetActionWeights: Array.from({ length: 5 }, (_, actionIndex) => finiteArray(arrayAt(source, 'targetActionWeights', 'target_action_weights')[actionIndex], 16)), values: finiteArray(valueAt(source, 'values', 'stateValues', 'state_values'), 16), actionValues: Array.from({ length: 16 }, (_, state) => finiteArray(rawActionValues[state], 5)), policy: rawPolicy, policyProbabilities: Array.from({ length: 16 }, (_, state) => finiteArray(arrayAt(source, 'policyProbabilities', 'policy_probabilities', 'probabilities')[state], 5)), lastFeatures: finiteArray(valueAt(source, 'lastFeatures', 'last_features'), 16), lastState: numberAt(source, 0, 'lastState', 'last_state'), lastAction: action(valueAt(source, 'lastAction', 'last_action'), 255), lastPrediction: numberAt(source, 0, 'lastPrediction', 'last_prediction'), lastTarget: numberAt(source, 0, 'lastTarget', 'last_target'), lastTdError: numberAt(source, 0, 'lastTdError', 'last_td_error'), lastLoss: numberAt(source, 0, 'lastLoss', 'last_loss'), lastGradientNorm: numberAt(source, 0, 'lastGradientNorm', 'last_gradient_norm'), lastUpdateNorm: numberAt(source, 0, 'lastUpdateNorm', 'last_update_norm'), replaySize: numberAt(source, 0, 'replaySize', 'replay_size'), updateCount: numberAt(source, 0, 'updateCount', 'update_count'), targetSyncCount: numberAt(source, 0, 'targetSyncCount', 'target_sync_count'), episodeCount: numberAt(source, 0, 'episodeCount', 'episode_count'), totalSteps: numberAt(source, 0, 'totalSteps', 'total_steps'), episodeReturnMean: numberAt(source, 0, 'episodeReturnMean', 'episode_return_mean'), episodeReturnVariance: numberAt(source, 0, 'episodeReturnVariance', 'episode_return_variance'), converged: boolAt(source, false, 'converged'), truncated: boolAt(source, false, 'truncated'), exhausted: boolAt(source, false, 'exhausted') } }
function normalizeEpisode(value: unknown, fallbackNumber: number): ValueFunctionEpisode { const source = record(value); const rawSteps = arrayAt(source, 'steps', 'trajectory', 'transitions'); const rawUpdates = arrayAt(source, 'updates'); return { number: numberAt(source, fallbackNumber, 'number', 'episode'), steps: rawSteps.map((row, index) => normalizeTransition(row, index)), updates: rawUpdates.map((row, index) => normalizeUpdate(row, index)), totalReturn: numberAt(source, 0, 'totalReturn', 'total_return', 'return'), discountedReturn: numberAt(source, 0, 'discountedReturn', 'discounted_return'), length: numberAt(source, rawSteps.length, 'length'), done: boolAt(source, false, 'done', 'terminated'), truncated: boolAt(source, false, 'truncated') } }
function normalizeOutcome(value: unknown, fallback: ValueFunctionConfig): ValueFunctionOutcome | ValueFunctionAdvanceOutcome { const source = record(value); const snapshot = normalizeSnapshot(valueAt(source, 'snapshot'), fallback); const rawTransitions = arrayAt(source, 'transitions'); const rawUpdates = arrayAt(source, 'updates'); const rawEpisodes = arrayAt(source, 'episodes'); if (rawTransitions.length || rawEpisodes.length) return { snapshot, transitions: rawTransitions.map((row, index) => normalizeTransition(row, index)), updates: rawUpdates.map((row, index) => normalizeUpdate(row, index)), episodes: rawEpisodes.map((row, index) => normalizeEpisode(row, index + 1)) }; const transition = normalizeTransition(valueAt(source, 'transition', 'step'), snapshot.totalSteps > 0 ? snapshot.totalSteps - 1 : 0); return { snapshot, transition, updates: rawUpdates.map((row, index) => normalizeUpdate(row, index)), ...(valueAt(source, 'episode') ? { episode: normalizeEpisode(valueAt(source, 'episode'), snapshot.episodeCount) } : {}) } }
function audit(snapshot: ValueFunctionSnapshot, outcome?: ValueFunctionOutcome | ValueFunctionAdvanceOutcome): ValueFunctionAudit { const rows = outcome && 'transition' in outcome ? [outcome.transition] : outcome?.transitions ?? []; const finite = [...snapshot.values, ...snapshot.weights, ...snapshot.actionValues.flat(), ...snapshot.actionWeights.flat()].every(Number.isFinite); const featuresFinite = snapshot.lastFeatures.every(Number.isFinite); const replayUniform = snapshot.mode !== 'deep_q' || snapshot.replaySize >= 0; return { finite, featuresFinite, replayUniform, targetNetworkVisible: snapshot.mode !== 'deep_q' || snapshot.targetSyncCount >= 0, updateCount: outcome?.updates.length ?? 0, message: rows.length === 0 ? 'No transition has been sampled yet.' : undefined } }
function post(response: ValueFunctionWorkerResponse): void { scope.postMessage(response) }
function errorResponse(error: unknown, recoverable = true): void { const message = error instanceof Error ? error.message : String(error); post({ v: VALUE_FUNCTION_PROTOCOL_VERSION, runId: activeRunId || undefined, kind: 'error', sequence: ++sequence, code: 'value_function_worker', message, recoverable }) }
async function start(request: Extract<ValueFunctionWorkerRequest, { kind: 'start' }>): Promise<void> { const validation = valueFunctionConfigValidationError(request.config); if (validation) { errorResponse(new Error(validation.message)); return }; await ensureInit(); evaluator?.free?.(); config = { ...request.config, mode: canonicalValueFunctionMode(request.config.mode) ?? request.config.mode, featureMap: canonicalValueFunctionFeatureMap(request.config.featureMap) ?? request.config.featureMap }; evaluator = instantiate(config); activeRunId = request.runId; sequence = 0; if (request.restoreEpisodes && request.restoreEpisodes > 0) for (let index = 0; index < Math.min(Math.trunc(request.restoreEpisodes), config.maxEpisodes); index += 1) call(evaluator, ['step', 'episode']); const snapshot = normalizeSnapshot(call(evaluator, ['snapshot']), config); post({ v: VALUE_FUNCTION_PROTOCOL_VERSION, runId: activeRunId, kind: 'started', sequence: ++sequence, snapshot, engineVersion: 'value-function-v1' }) }
function result(raw: unknown): void { if (!config) throw new Error('value-function evaluator has not started'); const outcome = normalizeOutcome(raw, config); post({ v: VALUE_FUNCTION_PROTOCOL_VERSION, runId: activeRunId, kind: 'result', sequence: ++sequence, outcome, audit: audit(outcome.snapshot, outcome) }) }
async function handle(request: ValueFunctionWorkerRequest): Promise<void> { if (request.v !== VALUE_FUNCTION_PROTOCOL_VERSION) return; if (request.kind === 'start') { await start(request); return }; if (request.runId !== activeRunId || !evaluator || !config) return; if (request.kind === 'reset') { const snapshot = normalizeSnapshot(call(evaluator, ['reset'], request.seedHex ?? null), config); post({ v: VALUE_FUNCTION_PROTOCOL_VERSION, runId: activeRunId, kind: 'reset', sequence: ++sequence, snapshot, audit: audit(snapshot) }); return }; if (request.kind === 'step') { result(call(evaluator, ['step', 'iteration', 'episode'])); return }; if (request.kind === 'advance') { result(call(evaluator, ['advance', 'runIterations', 'run_iterations'], Math.max(1, Math.min(2_000, Math.trunc(request.transitions))))); return }; result(call(evaluator, ['advance', 'runToCompletion', 'run_to_completion'], 100)) }
scope.addEventListener('message', (event: MessageEvent<ValueFunctionWorkerRequest>) => { void handle(event.data).catch((error: unknown) => errorResponse(error, false)) })
